version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - ES_HEAP_SIZE=2g
      - MAX_OPEN_FILES=1065535
      - MAX_LOCKED_MEMORY=unlimited
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    restart: unless-stopped
    volumes:
      - type: volume
        source: logs
        target: /var/log
      - type: volume
        source: data
        target: /usr/share/elasticsearch/data
    networks:
      - ahmia-net
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - 5601:5601
    volumes:
      - type: volume
        source: logs
        target: /var/log
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    restart: unless-stopped
    networks:
      - ahmia-net

volumes:
  data:
  logs:

networks:
  ahmia-net: